# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/ouya/cardhu/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/ouya/cardhu/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
        vendor/ouya/cardhu/proprietary/bin/unimac:system/bin/unimac \
        vendor/ouya/cardhu/proprietary/bin/rm_ts_server:system/bin/rm_ts_server \
        vendor/ouya/cardhu/proprietary/bin/tf_daemon:system/bin/tf_daemon \
        vendor/ouya/cardhu/proprietary/etc/firmware/bcm4330.hcd:system/etc/firmware/bcm4330.hcd \
        vendor/ouya/cardhu/proprietary/etc/firmware/nvavp_aud_ucode.bin:system/etc/firmware/nvavp_aud_ucode.bin \
        vendor/ouya/cardhu/proprietary/etc/firmware/nvavp_os_0ff00000.bin:system/etc/firmware/nvavp_os_0ff00000.bin \
	vendor/ouya/cardhu/proprietary/etc/firmware/nvavp_os_00001000.bin:system/etc/firmware/nvavp_os_00001000.bin \
        vendor/ouya/cardhu/proprietary/etc/firmware/nvavp_os_eff00000.bin:system/etc/firmware/nvavp_os_eff00000.bin \
        vendor/ouya/cardhu/proprietary/etc/firmware/nvavp_vid_ucode_alt.bin:system/etc/firmware/nvavp_vid_ucode_alt.bin \
        vendor/ouya/cardhu/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
        vendor/ouya/cardhu/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
        vendor/ouya/cardhu/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
        vendor/ouya/cardhu/proprietary/lib/hw/gralloc.tegra3.so:system/lib/hw/gralloc.tegra3.so \
        vendor/ouya/cardhu/proprietary/lib/hw/hwcomposer.tegra3.so:system/lib/hw/hwcomposer.tegra3.so \
        vendor/ouya/cardhu/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
        vendor/ouya/cardhu/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
        vendor/ouya/cardhu/proprietary/lib/libnvapputil.so:system/lib/libnvapputil.so \
        vendor/ouya/cardhu/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
        vendor/ouya/cardhu/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
        vendor/ouya/cardhu/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
        vendor/ouya/cardhu/proprietary/lib/libnvcamerahdr.so:system/lib/libnvcamerahdr.so \
        vendor/ouya/cardhu/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
        vendor/ouya/cardhu/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
        vendor/ouya/cardhu/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
	vendor/ouya/cardhu/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmmlite_image.so:system/lib/libnvmmlite_image.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
	vendor/ouya/cardhu/proprietary/lib/libnvmm_misc.so:system/lib/libnvmm_misc.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
        vendor/ouya/cardhu/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
        vendor/ouya/cardhu/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
        vendor/ouya/cardhu/proprietary/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
        vendor/ouya/cardhu/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
        vendor/ouya/cardhu/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
        vendor/ouya/cardhu/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
        vendor/ouya/cardhu/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
        vendor/ouya/cardhu/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
        vendor/ouya/cardhu/proprietary/lib/libnvos.so:system/lib/libnvos.so \
        vendor/ouya/cardhu/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
        vendor/ouya/cardhu/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
        vendor/ouya/cardhu/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
        vendor/ouya/cardhu/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
        vendor/ouya/cardhu/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
        vendor/ouya/cardhu/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
        vendor/ouya/cardhu/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
        vendor/ouya/cardhu/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
        vendor/ouya/cardhu/proprietary/vendor/firmware/bcm4330/fw_bcmdhd_apsta.bin:system/vendor/firmware/bcm4330/fw_bcmdhd_apsta.bin \
        vendor/ouya/cardhu/proprietary/vendor/firmware/bcm4330/fw_bcmdhd.bin:system/vendor/firmware/bcm4330/fw_bcmdhd.bin \
	vendor/ouya/cardhu/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
	vendor/ouya/cardhu/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
	vendor/ouya/cardhu/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
	vendor/ouya/cardhu/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so
